config/routes.rb
Rails.application.routes.draw do
  resources :translates do
    collection do
      get :get_translate
    end
  end
  resources :me_demos do
    collection do
      get :grab
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/me_demo.rb
class MeDemo < ApplicationRecord
end

app/models/translate.rb
class Translate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/me_demos_controller.rb
# -*- encoding : utf-8 -*-
class MeDemosController < ApplicationController
  before_action :set_me_demo, only: [:show, :edit, :update, :destroy]

  # GET /me_demos
  # GET /me_demos.json
  def index
    @me_demos = MeDemo.all
  end

  # GET /me_demos/1
  # GET /me_demos/1.json
  def show
  end

  # GET /me_demos/new
  def new
    @me_demo = MeDemo.new
  end

  def grab
    require 'product'
    products = Product.new.fetch_start()

    render json: { title: products[:title], product_color: products[:pcolor], size_infos: products[:psizes], product_info: products[:pinfos] }
  end

  # GET /me_demos/1/edit
  def edit
  end

  # POST /me_demos
  # POST /me_demos.json
  def create
    @me_demo = MeDemo.new(me_demo_params)

    respond_to do |format|
      if @me_demo.save
        format.html { redirect_to @me_demo, notice: 'Me demo was successfully created.' }
        format.json { render :show, status: :created, location: @me_demo }
      else
        format.html { render :new }
        format.json { render json: @me_demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /me_demos/1
  # PATCH/PUT /me_demos/1.json
  def update
    respond_to do |format|
      if @me_demo.update(me_demo_params)
        format.html { redirect_to @me_demo, notice: 'Me demo was successfully updated.' }
        format.json { render :show, status: :ok, location: @me_demo }
      else
        format.html { render :edit }
        format.json { render json: @me_demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /me_demos/1
  # DELETE /me_demos/1.json
  def destroy
    @me_demo.destroy
    respond_to do |format|
      format.html { redirect_to me_demos_url, notice: 'Me demo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_me_demo
      #@me_demo = MeDemo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def me_demo_params
      params.require(:me_demo).permit(:me_text)
    end
end

app/controllers/translates_controller.rb
# -*- encoding : utf-8 -*-
class TranslatesController < ApplicationController
  before_action :set_translate, only: [:show, :edit, :update, :destroy]

  # GET /translates
  # GET /translates.json
  def index
    @translates = Translate.all
    require 'translation_tool'
    @languages = TranslationTool.new.option_list()
  end

  # GET /translates/1
  # GET /translates/1.json
  def show
  end

  # GET /translates/new
  def new
    @translate = Translate.new
  end

  # GET /translates/1/edit
  def edit
  end

  # POST /translates
  # POST /translates.json
  # POST /translations
  # POST /translations.json
  def create
    @translation = Translation.new(translation_params)

    require 'translation_tool'
    @result = ""
    query = translation_params[:input_text]
    begin
      if query.present?
        @result = TranslationTool.new.start(query)
      end
    rescue Exception => e
      Rails.logger.error e
      Rails.logger.error e.backtrace.join("\n")
    end


    respond_to do |format|
      format.html { render :edit }
    end
  end

  def get_translate
    require 'translation_tool'
    totaltimes = 1.5*1000
    # (0..1000).each do |t|
    @results = TranslationTool.new.start_google(params[:q], params[:tl])
    p "************"
    p @results
    p "************"
      # sleep(2)
    # end
    @languages = TranslationTool.new.option_list()
    render :index
  end

  # PATCH/PUT /translates/1
  # PATCH/PUT /translates/1.json
  def update
    respond_to do |format|
      if @translate.update(translate_params)
        format.html { redirect_to @translate, notice: 'Translate was successfully updated.' }
        format.json { render :show, status: :ok, location: @translate }
      else
        format.html { render :edit }
        format.json { render json: @translate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translates/1
  # DELETE /translates/1.json
  def destroy
    @translate.destroy
    respond_to do |format|
      format.html { redirect_to translates_url, notice: 'Translate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translate
      @translate = Translate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translate_params
      params.require(:translate).permit(:q, :text, :tl)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/me_demos_helper.rb
module MeDemosHelper
end

app/helpers/translates_helper.rb
module TranslatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mechanize</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_include_tag 'manifest.js' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
<%= yield %>
</body>
</html>

app/views/me_demos/_form.html.erb
<%= form_with(model: me_demo, local: true) do |form| %>
  <% if me_demo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(me_demo.errors.count, "error") %> prohibited this me_demo from being saved:</h2>

      <ul>
        <% me_demo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :me_text %>
    <%= form.text_field :me_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/me_demos/edit.html.erb
<%= javascript_pack_tag 'app' %>
<div>
  <div style="text-align: center;">
    <h4>产品信息修改</h4>
  </div>

  <div class="top-button">
    <%= link_to '返回', me_demos_path %>
  </div>
</div>
<style>
  .top-button {
    position: absolute;
    top: 24px;
    z-index: 1;
    right: 10px;
  }
</style>

app/views/me_demos/grab.html.erb
<div style="text-align: center;">
  <h1>产品信息修改</h1>
</div>

<div style="position: fixed">
  <Application></Application>
  <%= link_to '返回', me_demos_path %>
</div>

app/views/me_demos/index.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<!--<h1>Me Demos</h1>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Me text</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<%# @me_demos.each do |me_demo| %>
<!--      <tr>-->
<!--        <td><%#= me_demo.me_text %></td>-->
<!--        <td><%#= link_to 'Show', me_demo %></td>-->
<!--        <td><%#= link_to 'Edit', edit_me_demo_path(me_demo) %></td>-->
<!--        <td><%#= link_to 'Destroy', me_demo, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<%# end %>
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<!--<%#= link_to 'New Me Demo', new_me_demo_path %><br/>-->
<%= link_to '修改产品', edit_me_demo_path(0) %>
<br/>
<%= link_to '翻译', translates_path %>

app/views/me_demos/new.html.erb
<h1>New Me Demo</h1>

<%= render 'form', me_demo: @me_demo %>

<%= link_to 'Back', me_demos_path %>

app/views/me_demos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Me text:</strong>
  <%= @me_demo.me_text %>
</p>

<%= link_to 'Edit', edit_me_demo_path(@me_demo) %> |
<%= link_to 'Back', me_demos_path %>

app/views/translates/_form.html.erb
<div class="translation">
  <%= form_with(model: translation, local: true) do |form| %>
    <% if translation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(translation.errors.count, "error") %> prohibited this translation from being saved:</h2>
        <ul>
          <% translation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :input_text %>
      <%= form.text_area :input_text, :cols => 50, :rows => 10 %>
    </div>
    <div class="actions">
      <%= form.submit 'Translate' %>
    </div>
    <% if @result.present? %>
      <div>
        翻译结果为：
        <p class="result"><%= @result['trans_result'].first['dst'] %></p>
      </div>
    <% end %>
  <% end %>
</div>

<style>
  .translation {
    font-size: 20px;
  }

  .result {
    color: #cc0000;
  }
</style>

app/views/translates/edit.html.erb
<h1>Editing Translation</h1>

<%= render 'form', translation: @translation %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translates/index.html.erb
<div class="translation">
  <h3>Google批量翻译</h3>
  <div class="translate-content">
    <% if params[:q].present? %>
      <% params[:q].split("✚").each do |q| %>
        <textarea rows="5" cols="50" placeholder="请输入需要翻译的内容"><%= q %></textarea>
      <% end %>
    <% else %>
      <textarea rows="5" cols="50" placeholder="请输入需要翻译的内容"></textarea>
    <% end %>
  </div>
  <div style="margin-bottom: 50px;">
    <button onclick="addTranslate()">新增内容</button>
  </div>
  <select id="tta_tgtsl" style="width: 113px;" aria-label="输出语言选择下拉菜单">
    <% @languages.each do |language| %>
      <%
        selected = ""
        if language[:value] == params[:tl]
          selected = "selected"
        else
          if language[:value] == 'en'
            selected = "selected"
          end
        end
      %>
      <option value="<%=language[:value] %>" <%=selected %>><%=language[:name] %></option>
      <%  %>
    <% end %>
  </select>
  <input name="Query" type="button" value="翻译" onclick="trans_late();">

  <% if @results.present? %>
    <h3>翻译的结果为：</h3>
    <% @results.each_with_index do |result, index| %>
      <p class="notice">第<%= index+1 %>次    <%= result %></p><br/>
    <% end %>
  <% end %>

  <p>
    <%= link_to '百度翻译', new_translate_path %>
    <%= link_to '返回', me_demos_path %>
    <%= link_to '刷新', translates_path %>
  </p>
</div>
<script type="text/javascript">
    function trans_late() {
        let translateContents = [];
        let tta = document.getElementsByTagName('textarea')
        for (var i = 0; i < tta.length; i++) {
            if (tta[i].value) {
                translateContents.push(tta[i].value);
            }
        }
        // |, ||, ↵,0(ko), ↓，→，↕，ϟ，Φ
        window.location.href = "/translates/get_translate?q=" + translateContents.join("✚") + "&tl=" + document.getElementById('tta_tgtsl').value;
    }

    function addTranslate() {
        $(".translate-content").append('<textarea rows="5" cols="50" placeholder="请输入需要翻译的内容"></textarea>')
    }
</script>

<style>
  textarea {
    margin-left: 5px;
  }
</style>

app/views/translates/new.html.erb
<h1>Translation</h1>

<%= render 'form', translation: @translate %>

<%= link_to 'Back', translates_path %>

app/views/translates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Input text:</strong>
  <%= @translation.input_text %>
</p>

<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>